apiVersion: batch/v1
kind: Job
metadata:
  name: ks-devops-db-ctrl-job
  namespace: kubesphere-devops-system
  labels:
    app: ks-devops-apiserver
    job: ks-devops-db-ctrl
    version: latest
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: ks-devops-apiserver
        job: ks-devops-db-ctrl
        version: latest
      name: ks-devops-db-ctrl
    spec:
      initContainers:
      - name: wait-mysql
        image: alpine:3.10.4
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'until nc -z mysql.kubesphere-system.svc 3306; do echo "waiting for mysql"; sleep 2; done;']
      containers:
      - command: ["/flyway/flyway", "-X", "-url=jdbc:mysql://mysql.kubesphere-system.svc/devops", "-user=root", "-validateOnMigrate=false", "-locations=filesystem:/flyway/sql/devops", "migrate"]
        env:
        - name: FLYWAY_PASSWORD
          value: "password"
        image: kubesphere/ks-devops:flyway-v2.1.0
        imagePullPolicy: IfNotPresent
        name: devops-db-ctrl
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
