
---
# Source: jenkins-update-center/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: uc-jenkins-update-center
  labels:
    app: jenkins-update-center
    chart: jenkins-update-center-0.8.0
    release: uc
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: jenkins-update-center
    release: uc
---
# Source: jenkins-update-center/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc-jenkins-update-center
  labels:
    app: jenkins-update-center
    chart: jenkins-update-center-0.8.0
    release: uc
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-update-center
      release: uc
  template:
    metadata:
      labels:
        app: jenkins-update-center
        release: uc
    spec:
      initContainers:
        - name: "init-jenkins-update-center"
          image: "kubesphere/jenkins-uc:v2.1.1"
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "cp -r -f /webroot/* /jenkins-plugins"
          volumeMounts:
            - name: webroot
              mountPath: "/jenkins-plugins"
      imagePullSecrets:
      - name: qingcloud 
      containers:
        - name: jenkins-update-center
          image: "nginx:1.14-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: webroot
              mountPath: /usr/share/nginx/html
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {}
            
      volumes:
      - name: webroot
        emptyDir: {}
