apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ks-apigateway
    tier: backend
    version: 2.1.1
  name: ks-apigateway
  namespace: kubesphere-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks-apigateway
      tier: backend
      version: 2.1.1
  template:
    metadata:
      labels:
        app: ks-apigateway
        tier: backend
        version: 2.1.1
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - export KUBESPHERE_TOKEN=`cat /var/run/secrets/kubernetes.io/serviceaccount/token` && ks-apigateway --conf=/etc/caddy/Caddyfile --log=stderr
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt-secret
              name: ks-account-secret
        image: hyc94/ks-apigateway:v2.1.1.1
        imagePullPolicy: IfNotPresent
        name: ks-apigateway
        ports:
        # apiserver
        - containerPort: 2018
          protocol: TCP
        resources:
          limits:
            cpu: 1
            memory: 500Mi
          requests:
            cpu: 20m
            memory: 100Mi
        volumeMounts:
        - mountPath: /etc/caddy
          name: caddyfile
        - mountPath: /etc/kubesphere
          name: kubesphere-config
      serviceAccount: kubesphere
      serviceAccountName: kubesphere
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 60
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 60
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - ""
      volumes:
      - configMap:
          defaultMode: 420
          name: caddyfile
        name: caddyfile
      - configMap:
          defaultMode: 420
          name: kubesphere-config
        name: kubesphere-config

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: ks-apigateway
    tier: backend
    version: 2.1.1
  name: ks-apigateway
  namespace: kubesphere-system
spec:
  ports:
  - name: 80-2018
    port: 80
    protocol: TCP
    targetPort: 2018
  selector:
    app: ks-apigateway
    tier: backend
    version: 2.1.1
  type: ClusterIP